name: React Frontend CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  EC2_TARGET_DIR: /var/www/frontend

jobs:

  build-and-deploy:
    name: Build & Deploy React
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create .env
        run: |
          echo "${{ secrets.REACT_ENV_FILE }}" > .env

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Verify Node
        run: |
          node -v
          npm -v

      - name: Install Dependencies
        run: npm ci

      - name: Build React
        run: npm run build

      - name: Verify Build
        run: |
          ls -la
          ls -la dist

      - name: Create Deployment Archive
        run: |
          tar -czf frontend.tar.gz -C dist .

      - name: Verify Archive
        run: |
          ls -lh frontend.tar.gz

      - name: Copy Archive to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "frontend.tar.gz"
          target: "/tmp"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            set -e

            echo "===== START DEPLOY ====="

            sudo mkdir -p /var/www/frontend

            sudo rm -rf /var/www/frontend/*

            sudo tar -xzf /tmp/frontend.tar.gz -C /var/www/frontend

            rm -f /tmp/frontend.tar.gz

            echo "Files deployed:"
            ls -la /var/www/frontend

            sudo nginx -t

            sudo systemctl reload nginx

            echo "===== DEPLOY COMPLETE ====="